# Generated by Django 3.2.9 on 2021-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaycToken',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('token_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RklToken',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('token_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='addresstokens',
            name='bored_ape_yacht_token_count',
        ),
        migrations.RemoveField(
            model_name='addresstokens',
            name='rumble_kong_league_token_count',
        ),
        migrations.AddField(
            model_name='addresstokens',
            name='bored_ape_yacht',
            field=models.ManyToManyField(related_name='bored_ape_yacht', to='stats.BaycToken'),
        ),
        migrations.AddField(
            model_name='addresstokens',
            name='rumble_kong_league',
            field=models.ManyToManyField(related_name='rumble_kong_league', to='stats.BaycToken'),
        ),
    ]
