# Generated by Django 3.2.9 on 2021-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20211112_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstokens',
            name='rumble_kong_league',
            field=models.ManyToManyField(related_name='rumble_kong_league', to='stats.RklToken'),
        ),
    ]
