# Generated by Django 3.2.9 on 2021-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_addresstokens_rumble_kong_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstokens',
            name='fetching_stats',
            field=models.BooleanField(default=False),
        ),
    ]
