name: Game Site API

on:
  push:
    branches:
      - main
      - 'develop'
  pull_request:
    branches:
      - "*"
jobs:

  cancel-duplicate-workflow:
    name: Cancel Duplicate Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        name: "Cancel duplicate workflow runs"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  run-tests:
    name: Run Tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2.0.0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: psycopg2 prerequisites
        run: |
          sudo apt-get install python-dev libpq-dev

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Cache Pipenv virtualenv
        uses: actions/cache@v1
        id: pipenv-cache
        with:
          path: ~/.pipenv
          key: ${{ runner.os }}-pipenv-v4-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-v4-

      - name: Install Dependencies
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        env:
          PIPENV_NOSPIN: "true"
          WORKON_HOME: ~/.pipenv/virtualenvs
          PIPENV_CACHE_DIR: ~/.pipenv/pipcache
        run: pipenv install --dev

      - name: Lint with flake8
        env:
          PIPENV_NOSPIN: "true"
          WORKON_HOME: ~/.pipenv/virtualenvs
          PYTHONPATH: "."
        run: |
          pipenv run flake8 .

      - name: Test with Coverage
        env:
          PIPENV_NOSPIN: "true"
          WORKON_HOME: ~/.pipenv/virtualenvs
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_NAME: github_actions
          SECRET_KEY: very-secret-key
          PYTHONPATH: "."
          DJANGO_DEBUG: "False"
        run: |
          pipenv run coverage run --source=app/api --rcfile=.coveragerc  manage.py test --verbosity=2
          pipenv run coverage report -m

    needs: [cancel-duplicate-workflow]
